### PR TITLE
docs: fix typos

### PR DESCRIPTION
**Pull request by osrm**
Hello, I found a few typos and fixed them. Hope this fix helps.

### CODE REVIEW

**Comment by osrm** [comment]
I've also found that some of the link paths in the current documentation are invalid. I believe the paths are mixed up and unorganised as the current documentation is not fully written, would it be okay if I fix?

**Comment by mouseless0x** [comment]
Thank you for the PR :)

**Comment by justme519** [comment]
> I've also found that some of the link paths in the current documentation are invalid. I believe the paths are mixed up and unorganised as the current documentation is not fully written, would it be okay if I fix?

Yes

**Comment by justme519** [comment]
Yes sorry I’m new to this

**Pull request merged**
